# Generated by Django 3.1 on 2021-09-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.CharField(max_length=20, null=True)),
                ('actualizar', models.IntegerField(null=True)),
                ('sixpm_actualizar', models.IntegerField(null=True)),
                ('amazon_actualizar', models.IntegerField(null=True)),
                ('ebay_actualizar', models.IntegerField(null=True)),
                ('footlocker_actualizar', models.IntegerField(null=True)),
                ('nike_actualizar', models.IntegerField(null=True)),
                ('zappos_actualizar', models.IntegerField(null=True)),
                ('actualizados', models.IntegerField(null=True)),
                ('sixpm_actualizados', models.IntegerField(null=True)),
                ('amazon_actualizados', models.IntegerField(null=True)),
                ('ebay_actualizados', models.IntegerField(null=True)),
                ('footlocker_actualizados', models.IntegerField(null=True)),
                ('nike_actualizados', models.IntegerField(null=True)),
                ('zappos_actualizados', models.IntegerField(null=True)),
                ('creados', models.IntegerField(null=True)),
                ('sixpm_creados', models.IntegerField(null=True)),
                ('amazon_creados', models.IntegerField(null=True)),
                ('ebay_creados', models.IntegerField(null=True)),
                ('footlocker_creados', models.IntegerField(null=True)),
                ('nike_creados', models.IntegerField(null=True)),
                ('zappos_creados', models.IntegerField(null=True)),
                ('listos_subir_meli', models.IntegerField(null=True)),
                ('listos_subir_zyte', models.IntegerField(null=True)),
            ],
        ),
    ]
